# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07461224c865eae6c1609dee44d5086319768c0d8d72d6653d4ebcf60a9adcba146ea2a3c13f75cae67162ad916aa8ea235c01fc41965aa037826b1444244ead

test:
  secret_key_base: c3dfc9191bcdcf44882754eab751f80ec5ce7b48464cb6a5251e8e5b58a7516f6f2ca1f71115f82e64351a64b9832f05a769c188b31e40733ef2bd0d7388de08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
